version: "3.8"

services:
  ch_ma:
    image: mariadb:10.8.3
    container_name: ch_ma
    networks:
      - ch_net
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./db/:/var/lib/mysql

  ch_app:
    build:
      context: ./config/go/
      dockerfile: Dockerfile.prd
    container_name: ch_app
    networks:
      - ch_net
    ports:
      - 127.0.0.1:5901:5901
    volumes:
      - ./app/:/app/
    depends_on:
      - ch_ma

  ch_ng:
    build:
      context: ./config/nginx/
      dockerfile: Dockerfile
    container_name: ch_ng
    networks:
      - ch_net
    ports:
      - 0.0.0.0:80:80
    volumes:
      - ./app/static:/usr/share/nginx/html/static/
      - ./config/nginx:/etc/nginx/conf.d/
      - ./ng/logs:/var/log/nginx/
    depends_on:
      - ch_app

networks:
  ch_net:
    name: ch_net
